export const eventDetails = {
  coupleNames: "Alex & Sam",
  date: "Saturday, 20 June 2026",
  ceremonyTime: "15:00",
  venue: "The Greenhouse",
  city: "Sample City",
  rsvpDeadline: "1 May 2026",
};

export const sampleGuests = [
  {
    id: "sample-1",
    first_name: "Taylor",
    last_name: "River",
    email: null,
    attending: true,
    needs_accommodation: true,
    accommodation_notes: "Would like a family room if available",
    dietary_notes: "Vegetarian",
    travel_notes: "Needs shuttle info",
    song_request: "A favorite dance song",
    payment_status: "pending" as const,
    payment_amount: 120,
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-2",
    first_name: "Jordan",
    last_name: "Stone",
    email: null,
    attending: false,
    needs_accommodation: false,
    accommodation_notes: null,
    dietary_notes: null,
    travel_notes: null,
    song_request: null,
    payment_status: "not_needed" as const,
    payment_amount: null,
    created_at: new Date().toISOString(),
  },
];

export const copy = {
  en: {
    navHome: "Home",
    navRsvp: "RSVP",
    navTravel: "Travel",
    navStay: "Stay",
    navActivities: "Activities",
    navAdmin: "Admin",
    heroEyebrow: "Wedding Hub Template",
    heroTitle: "A calm place to run the whole wedding weekend.",
    heroText:
      "Customize the couple, schedule, travel notes, accommodation planning, guest payments, and RSVP workflow. Connect Supabase when you are ready to collect real responses.",
    ctaRsvp: "Open RSVP",
    ctaSetup: "View setup",
    dateLabel: "Date",
    venueLabel: "Venue",
    deadlineLabel: "RSVP deadline",
    registerTitle: "Guest RSVP",
    registerIntro: "Collect names, attendance, accommodation needs, dietary notes, travel notes, and a song request.",
    adminTitle: "Wedding Weekend Admin",
    demoMode: "Demo mode",
    configuredMode: "Supabase connected",
  },
  de: {
    navHome: "Start",
    navRsvp: "Rueckmeldung",
    navTravel: "Anreise",
    navStay: "Uebernachtung",
    navActivities: "Aktivitaeten",
    navAdmin: "Admin",
    heroEyebrow: "Wedding Hub Vorlage",
    heroTitle: "Ein ruhiger Ort fuer das ganze Hochzeitswochenende.",
    heroText:
      "Passe Paar, Ablauf, Reiseinfos, Uebernachtung, Zahlungen und Rueckmeldungen an. Verbinde Supabase, sobald echte Rueckmeldungen gesammelt werden sollen.",
    ctaRsvp: "Rueckmeldung oeffnen",
    ctaSetup: "Setup ansehen",
    dateLabel: "Datum",
    venueLabel: "Ort",
    deadlineLabel: "Rueckmeldefrist",
    registerTitle: "Rueckmeldung",
    registerIntro: "Sammle Namen, Teilnahme, Uebernachtungsbedarf, Essensnotizen, Reiseinfos und Musikwunsch.",
    adminTitle: "Hochzeitswochenende Admin",
    demoMode: "Demo-Modus",
    configuredMode: "Supabase verbunden",
  },
};

export type Language = keyof typeof copy;
